### ISSUE TITLE
Mettre le plugin sur l'espace des dépôts QGis

### ISSUE THREAD

**Issue by ngonthier** [IGNF/trainminator#48]

**Comment by ngonthier** [comment]
Cela est maintenant possible suite à #60

**Comment by CelestinHuet** [comment]
Le plugin est trop gros... A priori, on peut supprimer le répertoire docs ? Il date d'il y a deux ans et il contient un énorme chantier qui ne doit sans doute plus être compatible avec le code actuel

**Comment by CelestinHuet** [comment]
Il y a déjà un exemple de projet beaucoup plus léger dans le répertoire qgisproject_example. La seule chose qu'il y manque, ce sont les patches gris pour indiquer les zones déjà réalisées, mais cela ne me semble pas utile pour un chantier de démo

**Comment by ngonthier** [comment]
Il s'agit d'un projet mono date ? Est ce que l'on aurait un petit chantier bidates à rajouter pour avoir les deux à disposition ?

**Comment by CelestinHuet** [comment]
C'est un projet bidate

**Comment by LMartelet** [comment]
> @samysung et @LMartelet vous en pensez quoi ?
> 
> Pour ma part, je pense que l'on peut supprimer le répertoire docs pour la soumission plugin QGIS et ajouter au repo (non soumis sur QGIS une version zippé du chantier de test) ainsi qu'une mention dans le README sur comment télécharger ce chantier test. Je pense ça peut être utile quand même de l'avoir pour tester l'outil.
> 
> En outre, vous pouvez déplacer les deux documents Documentation_utilisateur.pdf et Documentation_developpeur.pdf si besoin (ainsi que les liens correspondants dans le README).

Ok pour supprimer le gros chantier dans doc. Et pareil pour les docs users et devs

**Comment by CelestinHuet** [comment]
Je crée la pull request alors

**Comment by CelestinHuet** [comment]
Je le modifie aussi

**Comment by LMartelet** [comment]
> en revnache, @CelestinHuet , ne serait-il pas préférable de mettre les champs qgisMinimumVersion et qgisMaximumVersion au plus sure? J'ai quelques doutes par exemple que trianminator fonctionne sur toutes les versions au dessus de 3 (à vrai dire j'ai vu des crashs avec une version en 3.16 je crois).

Je t'assure qu'en 3.16 la version qu'on a ne marche pas. Perso j'ai surtout fait en 3.34 et je crois qu'en 3.28 ça ne marche toujours pas (je fais un check rapide)

**Comment by CelestinHuet** [comment]
Je mets 3.34 en version minimale, comme ça on ne s'embête pas

**Comment by LMartelet** [comment]
En fait 3.28 ça à l'air de passer. Mais bon 3.34 on est certain que ça fonctionne bien 😄

**Comment by samysung** [comment]
3.34 est une LTR (support long terme), c'est peut-être mieux de se baser là-dessus en effet

**Comment by samysung** [comment]
@CelestinHuet , bon bah tu nous dit quand on peut tester le téléchargement de trainminator depuis le gestionaire de plugin Qgis :)!

**Comment by CelestinHuet** [comment]
bah pour l'instant : Web server is returning an unknown error

Le serveur qgis a l'air d'être planté...

**Comment by samysung** [comment]
Ils ont pas payé leurs mensualités AWS peut-être

**Comment by CelestinHuet** [comment]
De ce que je comprends, si on essaye d'ajouter un plugin trop gros, alors toutes les tentatives suivantes renvoient un "Web server is returning an unknown error" jusqu'à ce que l'on se reconnecte. J'ai supprimé le répertoire asset et le chantier qui restait. La limite devait sans doute être à 10 Mo. Si certains ont besoin de ces deux répertoires, ils iront les chercher sur le Github. Le plugin est en cours de validation

**Comment by samysung** [comment]
l'extension trainminator à partir du dépôt sur Qgis 3.34 semble fonctionner chez moi.
