### ISSUE TITLE
Merge la branch proto diff dans le main puis ouverture du code

### ISSUE THREAD

**Issue by ngonthier** [IGNF/trainminator#60]

**Comment by samysung** [comment]
j'avais oublié que la branche main avait été créé au moment de la création du repo github, indépendamment de l'ancienne forge gitlab qui n'en possédait pas. Il s'avère après tests qu'il est impossible de faire un rebase entre 2 branchs sans historiques commun (ou plutôt, le rebase se fait, mais sur un nouvel historique, et lorsqu'on veut faire une PR, github considére les 2 branches comme totalement indépendantes). Il existe des solutions sur net avec un merge forcé un peu sal. Etant donné que la branche main du guthub n'avait aucun intérêt historique ou de code, j'ai préféré faire simple: j'ai renommé la branche main en old_main, j'ai reonnomé la branche merge_to_main_2 (celle dérivée de proto_diff, avec un readme enrichi) en main, je lui ai attribué des règles de sécurité, puis je l'ai fait passé en branche par défaut. J'ai fait passé le dépôt en public. Le fichier de doc 
dévéloppeur est toujours dans le code, mais je l'ai mis aussi dans le wiki, je pense que c'est plus propre et plus maintenable d'avoir la documentation dévéloppeur sur le WIKI (https://github.com/IGNF/trainminator/wiki). Les 2 formes d'accès sont en tout cas disponibles. 
Il faut pour les développeurs / testeurs, supprimer votre branche locale main avec un git branch -d main, puis récupérer la nouvelle branche avec un git pull origin main.

**Comment by ngonthier** [comment]
Super merci pour ce travail Samy. Est ce que cela vous convient @CelestinHuet et @LMartelet ?

**Comment by LMartelet** [comment]
Pas très expérimenté sur Git mais ça m'a l'air cohérent et logique comme manière de faire donc OK pour moi 😄

**Comment by CelestinHuet** [comment]
C'est bon pour moi !

**Comment by samysung** [comment]
est-ce que vous souhaitez versioner le code, tagger les versions et créer des releases?

**Comment by ngonthier** [comment]
Je ne pense pas que l'idée soit de versionner le code. Notre besoin est juste de pouvoir avoir une version fonctionnelle et distribuable. Mais il n'y a pas d'objectif d'évolutions pour l'instant.

**Comment by CelestinHuet** [comment]
De manière indirecte, il est possible d'indiquer des versions dans le fichier metadata.txt. Le dépôt QGis conserve la liste des versions. Cela pourrait suffire. Par exemple : https://plugins.qgis.org/plugins/Samon-master/#plugin-versions

**Comment by ngonthier** [comment]
Très bien faisons comme cela.
